### ISSUE TITLE
Error with decimals in matrix transform

### ISSUE THREAD

**Issue by francodgstn** [yckart/Transe.js#2]
The error is due to a wrong regex that don't consider the decimal values. The solution (from http://stackoverflow.com/questions/5968227/get-the-value-of-webkit-transform-of-an-element-with-jquery) is to chenge the two regex in the Helper section by adding a `\.` after the character `[0-9`.

``` javascript
Helpers = {
 getUnit: function(val) { return (/[0-9\.]+([^ ,\)]*)(,*)/).exec(val); },
 getIdentifier: function(matrix){ return matrix.split('('); },
 matrixToArray: function(matrix){ return matrix.match(/(-?[0-9\.]+)/g); }
}
```

**Comment by yckart** [comment]
@francodgstn Ohw, shame on me... However, the funny part is, that [one of the answers](http://stackoverflow.com/a/14397066/1250044) on stackoverflow is mine :ghost: 

I'll fix it...

**Comment by francodgstn** [comment]
Sorry, but I think that I've used an old version of your plugin probably
the bug is not present in the last version, however use regex is more
elegant that use split :)

Anyway thanks for your code, bye

2013/9/11 Yannick Albert notifications@github.com

> @francodgstn https://github.com/francodgstn Owh, shame on me...
> However, the funny part is, that one of the answers on stackoverflow is
> from me [image: :ghost:]
> 
> I'll fix it...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/yckart/jquery.transe.js/issues/2#issuecomment-24223679
> .

## 

Franco D'Agostino

Hwal Moo Do (Korean Martial Art) Instuctor
IT Consultant and Developer
Phone: +39 338 8933337
Email: franco.dgstn@gmail.com

**Comment by yckart** [comment]
Ok, no problem!

If you can wait 30 minutes, I'll release a brand new version with some really nice features...
